In [1]:
import numpy as np

Creating Arrays

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
arr = np.array([[1,2,3],[4,5,7]])
arr

array([[1, 2, 3],
       [4, 5, 7]])

In [9]:
arr.shape

(2, 3)

In [12]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 7]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 7]])

In [28]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [29]:
for i in a:
    print(type(i))
    print(int(i))

<class 'numpy.float64'>
0
<class 'numpy.float64'>
0
<class 'numpy.float64'>
0


In [30]:
np.empty([2,2])

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [34]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [40]:
np.arange(1,5,1)

array([1, 2, 3, 4])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 7]])

Array Attributes

In [52]:
arr.shape,arr.ndim,arr.dtype,arr.size

((2, 3), 2, dtype('int64'), 6)

Indexing and slicing

In [62]:
a = np.array([[10,20,30],[40,50,60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [57]:
a[0,1],a[0][1]

(np.int64(20), np.int64(20))

In [60]:
a[1,:]

array([40, 50, 60])

In [61]:
a[:,2]

array([30, 60])

In [67]:
a[::,::-1]

array([[30, 20, 10],
       [60, 50, 40]])

In [71]:
a = a.astype(np.int16)
a,a.dtype

(array([[10, 20, 30],
        [40, 50, 60]], dtype=int16),
 dtype('int16'))

In [73]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x,y

(array([1, 2, 3]), array([4, 5, 6]))

In [74]:
x+y

array([5, 7, 9])

In [75]:
x-y

array([-3, -3, -3])

In [76]:
x*y

array([ 4, 10, 18])

In [77]:
x/y

array([0.25, 0.4 , 0.5 ])

In [79]:
x%y

array([1, 2, 3])

In [81]:
x**y

array([  1,  32, 729])

In [82]:
np.dot(x,y)

np.int64(32)

In [85]:
np.sum([x,y])

np.int64(21)

In [89]:
a = np.array([[10,20,30],[40,50,60]])
np.sum(a[:,1])

np.int64(70)

In [90]:
np.mean(a)

np.float64(35.0)

In [91]:
np.sum(a)/a.size

np.float64(35.0)

In [100]:
x= np.array([22,20,21])
np.std(x)

np.float64(0.816496580927726)

In [2]:
np.full((2,2),'a')

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [14]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
a = np.array([[10,20,30],[40,50,60]])
a


array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
a.reshape(3,2),a

(array([[10, 20],
        [30, 40],
        [50, 60]]),
 array([[10, 20, 30],
        [40, 50, 60]]))

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [31]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])

In [32]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.hstack([a.reshape(3,1),b.reshape(3,1)])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
np.vstack([a.reshape(3,1),b.reshape(3,1)])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])