In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])        # Shape: (3,)
b = np.array([[10], [20], [30]]) # Shape: (3,1)

In [14]:
a = a.reshape(1,3)
a.shape,b.shape 

((1, 3), (3, 1))

In [15]:
b+a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [18]:
np.dot(b,a)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [22]:
d = np.add(b,a)+5
d

array([[16, 17, 18],
       [26, 27, 28],
       [36, 37, 38]])

In [30]:
d.mean(axis=1)

array([17., 27., 37.])

In [31]:
(16+17+18)/3

17.0

In [32]:
# Element Wise Operations

a = np.array([1,2,3])
b = np.array([4,5,6])
a+b,a*b,a-b

(array([5, 7, 9]), array([ 4, 10, 18]), array([-3, -3, -3]))

In [34]:
# Scalar Operations
a*10,a+5

(array([10, 20, 30]), array([6, 7, 8]))

In [38]:
# Mathematical Functions
np.sqrt(a),np.exp(a),np.log(a+1)

(array([1.        , 1.41421356, 1.73205081]),
 array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([0.69314718, 1.09861229, 1.38629436]))

In [44]:
2**(2.718)

6.579600549699714

In [49]:
np.exp(2),(2.718*2.718)

(np.float64(7.38905609893065), 7.387524)

In [50]:
a,b

(array([1, 2, 3]), array([4, 5, 6]))

In [51]:
a>b

array([False, False, False])

In [52]:
b>a

array([ True,  True,  True])

In [58]:
a = np.array([[1], [2], [3]])   # Shape (3,1)
b = np.array([10, 20, 30]).reshape(1,3)

In [59]:
a.shape,b.shape

((3, 1), (1, 3))

In [62]:
a+b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [65]:
A,B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [66]:
A+B

array([[ 6,  8],
       [10, 12]])

In [67]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])